version: 1.0.{build}
image: Visual Studio 2019
environment:
  PROJECTNAME:
    secure: TXn+4FwXgqnWzXjW1NkU6LTyaJk2GfhNM2kvKzq0Oe8=
  ORGNAME:
    secure: JwKHzxmM+/3pEixMh4+ahdBP/WfaXu8ACXJc6jvs5Eo=
  PROJECTTOKEN:
    secure: 7AolUkwXviuDD/C9rN7tEQmo5FhiGR2mo/j0Xi8pSeAJO9xCv1cR/CQvCQ7mZbnB
  NUGETAPIKEY:
    secure: QCIByOE43mlTIP0wq3JN8cYAuOw0wkt6PdkM1DxqSOHl2KgqXCfZ6WkhaAOUOTIU
nuget:
  project_feed: true
  disable_publish_on_pr: true
  disable_publish_octopus: true

init:  
  - SET JAVA_HOME=C:\Program Files\Java\jdk15
  - SET PATH=%JAVA_HOME%\bin;%PATH%

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
- ps: >-
    dotnet restore ".\Log4net.Appender.InfluxDBSyslog.sln"

    nuget restore ".\Log4net.Appender.InfluxDBSyslog.sln"

    gitversion /l console /output buildserver /updateAssemblyInfo

    choco install "sonarscanner-msbuild-net46" -y

    SonarScanner.MSBuild.exe begin /k:"$env:PROJECTNAME" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:PROJECTTOKEN" /o:"$env:ORGNAME"
build:
  project: Log4net.Appender.InfluxDBSyslog.sln
  verbosity: minimal
after_build:
- ps: SonarScanner.MSBuild.exe end /d:"sonar.login=$env:PROJECTTOKEN"
- cmd: ECHO nuget pack src/Log4net.Appender.InfluxDBSyslog\Log4net.Appender.InfluxDBSyslog.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -Symbols -SymbolPackageFormat snupkg
- cmd: nuget pack src/Log4net.Appender.InfluxDBSyslog\Log4net.Appender.InfluxDBSyslog.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -Symbols -SymbolPackageFormat snupkg
- cmd: appveyor PushArtifact "Log4net.Appender.InfluxDBSyslog.%GitVersion_NuGetVersion%.nupkg"
- ps: nuget push "Log4net.Appender.InfluxDBSyslog.$env:GitVersion_NuGetVersion.nupkg" -Source https://api.nuget.org/v3/index.json -apikey $env:NUGETAPIKEY
notifications:
- provider: Email
  to:
  - mburton@dennemeyer.com
  - mark.burton@zither-it.co.uk
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false